# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Studies/Embedded/FPGA/BasicToAdvanced/SPI/SPI.srcs/sources_1/ip/clockSetup/clockSetup.xci
# IP: The module: 'clockSetup' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Studies/Embedded/FPGA/BasicToAdvanced/SPI/SPI.gen/sources_1/ip/clockSetup/clockSetup_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clockSetup'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Studies/Embedded/FPGA/BasicToAdvanced/SPI/SPI.gen/sources_1/ip/clockSetup/clockSetup.xdc
# XDC: The top module name and the constraint reference have the same name: 'clockSetup'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Studies/Embedded/FPGA/BasicToAdvanced/SPI/SPI.gen/sources_1/ip/clockSetup/clockSetup_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clockSetup'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Studies/Embedded/FPGA/BasicToAdvanced/SPI/SPI.srcs/sources_1/ip/clockSetup/clockSetup.xci
# IP: The module: 'clockSetup' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Studies/Embedded/FPGA/BasicToAdvanced/SPI/SPI.gen/sources_1/ip/clockSetup/clockSetup_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clockSetup'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Studies/Embedded/FPGA/BasicToAdvanced/SPI/SPI.gen/sources_1/ip/clockSetup/clockSetup.xdc
# XDC: The top module name and the constraint reference have the same name: 'clockSetup'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Studies/Embedded/FPGA/BasicToAdvanced/SPI/SPI.gen/sources_1/ip/clockSetup/clockSetup_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clockSetup'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
