set_property PACKAGE_PIN W5 [get_ports sys_clk]
set_property IOSTANDARD LVCMOS33 [get_ports sys_clk]
create_clock -period 10.000 -name sys_clk_pin -waveform {0.000 5.000} -add [get_ports sys_clk]


set_property PACKAGE_PIN J1 [get_ports {pinOut_0}]
set_property IOSTANDARD LVCMOS33 [get_ports {pinOut_0}]

set_property PACKAGE_PIN U18 [get_ports reset]
set_property IOSTANDARD LVCMOS33 [get_ports reset]
set_property PACKAGE_PIN U16 [get_ports {gpio_io_i[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_io_i[0]}]
set_property PACKAGE_PIN E19 [get_ports {gpio_io_i[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_io_i[1]}]
set_property PACKAGE_PIN U19 [get_ports {gpio_io_i[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_io_i[2]}]
set_property PACKAGE_PIN V19 [get_ports {gpio_io_i[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_io_i[3]}]
set_property PACKAGE_PIN W18 [get_ports {gpio_io_i[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_io_i[4]}]
set_property PACKAGE_PIN U15 [get_ports {gpio_io_i[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_io_i[5]}]
set_property PACKAGE_PIN U14 [get_ports {gpio_io_i[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_io_i[6]}]
set_property PACKAGE_PIN V14 [get_ports {gpio_io_i[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_io_i[7]}]
set_property PACKAGE_PIN V13 [get_ports {gpio_io_i[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_io_i[8]}]
set_property PACKAGE_PIN V3 [get_ports {gpio_io_i[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_io_i[9]}]
set_property PACKAGE_PIN W3 [get_ports {gpio_io_i[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_io_i[10]}]
set_property PACKAGE_PIN U3 [get_ports {gpio_io_i[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_io_i[11]}]
set_property PACKAGE_PIN P3 [get_ports {gpio_io_i[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_io_i[12]}]
set_property PACKAGE_PIN N3 [get_ports {gpio_io_i[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_io_i[13]}]
set_property PACKAGE_PIN P1 [get_ports {gpio_io_i[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_io_i[14]}]
set_property PACKAGE_PIN L1 [get_ports {gpio_io_i[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_io_i[15]}]

set_property PACKAGE_PIN B18 [get_ports rx]
set_property IOSTANDARD LVCMOS33 [get_ports rx]
set_property PACKAGE_PIN A18 [get_ports tx]
set_property IOSTANDARD LVCMOS33 [get_ports tx]