# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Studies/FPGA/practice/test/ultraSonic/ultraSonic.srcs/sources_1/ip/clkSetup/clkSetup.xci
# IP: The module: 'clkSetup' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Studies/FPGA/practice/test/ultraSonic/ultraSonic.gen/sources_1/ip/clkSetup/clkSetup_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clkSetup'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Studies/FPGA/practice/test/ultraSonic/ultraSonic.gen/sources_1/ip/clkSetup/clkSetup.xdc
# XDC: The top module name and the constraint reference have the same name: 'clkSetup'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Studies/FPGA/practice/test/ultraSonic/ultraSonic.gen/sources_1/ip/clkSetup/clkSetup_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clkSetup'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Studies/FPGA/practice/test/ultraSonic/ultraSonic.srcs/sources_1/ip/clkSetup/clkSetup.xci
# IP: The module: 'clkSetup' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Studies/FPGA/practice/test/ultraSonic/ultraSonic.gen/sources_1/ip/clkSetup/clkSetup_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clkSetup'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Studies/FPGA/practice/test/ultraSonic/ultraSonic.gen/sources_1/ip/clkSetup/clkSetup.xdc
# XDC: The top module name and the constraint reference have the same name: 'clkSetup'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Studies/FPGA/practice/test/ultraSonic/ultraSonic.gen/sources_1/ip/clkSetup/clkSetup_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clkSetup'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
