# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/new/master.xdc

# Block Designs: bd/micro/micro.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==micro || ORIG_REF_NAME==micro} -quiet] -quiet

# IP: bd/micro/ip/micro_axi_uartlite_0_0/micro_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==micro_axi_uartlite_0_0 || ORIG_REF_NAME==micro_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/micro/ip/micro_axi_gpio_0_0/micro_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==micro_axi_gpio_0_0 || ORIG_REF_NAME==micro_axi_gpio_0_0} -quiet] -quiet

# IP: bd/micro/ip/micro_myGPIO_0_0/micro_myGPIO_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==micro_myGPIO_0_0 || ORIG_REF_NAME==micro_myGPIO_0_0} -quiet] -quiet

# IP: bd/micro/ip/micro_microblaze_0_0/micro_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==micro_microblaze_0_0 || ORIG_REF_NAME==micro_microblaze_0_0} -quiet] -quiet

# IP: bd/micro/ip/micro_dlmb_v10_0/micro_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==micro_dlmb_v10_0 || ORIG_REF_NAME==micro_dlmb_v10_0} -quiet] -quiet

# IP: bd/micro/ip/micro_ilmb_v10_0/micro_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==micro_ilmb_v10_0 || ORIG_REF_NAME==micro_ilmb_v10_0} -quiet] -quiet

# IP: bd/micro/ip/micro_dlmb_bram_if_cntlr_0/micro_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==micro_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==micro_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/micro/ip/micro_ilmb_bram_if_cntlr_0/micro_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==micro_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==micro_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/micro/ip/micro_lmb_bram_0/micro_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==micro_lmb_bram_0 || ORIG_REF_NAME==micro_lmb_bram_0} -quiet] -quiet

# IP: bd/micro/ip/micro_xbar_0/micro_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==micro_xbar_0 || ORIG_REF_NAME==micro_xbar_0} -quiet] -quiet

# IP: bd/micro/ip/micro_microblaze_0_axi_periph_0/micro_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==micro_microblaze_0_axi_periph_0 || ORIG_REF_NAME==micro_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/micro/ip/micro_microblaze_0_axi_intc_0/micro_microblaze_0_axi_intc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==micro_microblaze_0_axi_intc_0 || ORIG_REF_NAME==micro_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/micro/ip/micro_microblaze_0_xlconcat_0/micro_microblaze_0_xlconcat_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==micro_microblaze_0_xlconcat_0 || ORIG_REF_NAME==micro_microblaze_0_xlconcat_0} -quiet] -quiet

# IP: bd/micro/ip/micro_mdm_1_0/micro_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==micro_mdm_1_0 || ORIG_REF_NAME==micro_mdm_1_0} -quiet] -quiet

# IP: bd/micro/ip/micro_clk_wiz_1_0/micro_clk_wiz_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==micro_clk_wiz_1_0 || ORIG_REF_NAME==micro_clk_wiz_1_0} -quiet] -quiet

# IP: bd/micro/ip/micro_rst_clk_wiz_1_100M_0/micro_rst_clk_wiz_1_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==micro_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==micro_rst_clk_wiz_1_100M_0} -quiet] -quiet

# XDC: c:/Studies/Embedded/FPGA/BasicToAdvanced/microBlaze/microBlaze.gen/sources_1/bd/micro/micro_ooc.xdc
