# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/new/top.xdc

# Block Designs: bd/microBlazeWithSecond/microBlazeWithSecond.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==microBlazeWithSecond || ORIG_REF_NAME==microBlazeWithSecond} -quiet] -quiet

# IP: bd/microBlazeWithSecond/ip/microBlazeWithSecond_microblaze_0_0/microBlazeWithSecond_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==microBlazeWithSecond_microblaze_0_0 || ORIG_REF_NAME==microBlazeWithSecond_microblaze_0_0} -quiet] -quiet

# IP: bd/microBlazeWithSecond/ip/microBlazeWithSecond_axi_uartlite_0_0/microBlazeWithSecond_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==microBlazeWithSecond_axi_uartlite_0_0 || ORIG_REF_NAME==microBlazeWithSecond_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/microBlazeWithSecond/ip/microBlazeWithSecond_axi_gpio_0_0/microBlazeWithSecond_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==microBlazeWithSecond_axi_gpio_0_0 || ORIG_REF_NAME==microBlazeWithSecond_axi_gpio_0_0} -quiet] -quiet

# IP: bd/microBlazeWithSecond/ip/microBlazeWithSecond_mySecondIP_0_0/microBlazeWithSecond_mySecondIP_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==microBlazeWithSecond_mySecondIP_0_0 || ORIG_REF_NAME==microBlazeWithSecond_mySecondIP_0_0} -quiet] -quiet

# IP: bd/microBlazeWithSecond/ip/microBlazeWithSecond_dlmb_v10_0/microBlazeWithSecond_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==microBlazeWithSecond_dlmb_v10_0 || ORIG_REF_NAME==microBlazeWithSecond_dlmb_v10_0} -quiet] -quiet

# IP: bd/microBlazeWithSecond/ip/microBlazeWithSecond_ilmb_v10_0/microBlazeWithSecond_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==microBlazeWithSecond_ilmb_v10_0 || ORIG_REF_NAME==microBlazeWithSecond_ilmb_v10_0} -quiet] -quiet

# IP: bd/microBlazeWithSecond/ip/microBlazeWithSecond_dlmb_bram_if_cntlr_0/microBlazeWithSecond_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==microBlazeWithSecond_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==microBlazeWithSecond_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/microBlazeWithSecond/ip/microBlazeWithSecond_ilmb_bram_if_cntlr_0/microBlazeWithSecond_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==microBlazeWithSecond_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==microBlazeWithSecond_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/microBlazeWithSecond/ip/microBlazeWithSecond_lmb_bram_0/microBlazeWithSecond_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==microBlazeWithSecond_lmb_bram_0 || ORIG_REF_NAME==microBlazeWithSecond_lmb_bram_0} -quiet] -quiet

# IP: bd/microBlazeWithSecond/ip/microBlazeWithSecond_xbar_0/microBlazeWithSecond_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==microBlazeWithSecond_xbar_0 || ORIG_REF_NAME==microBlazeWithSecond_xbar_0} -quiet] -quiet

# IP: bd/microBlazeWithSecond/ip/microBlazeWithSecond_microblaze_0_axi_periph_0/microBlazeWithSecond_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==microBlazeWithSecond_microblaze_0_axi_periph_0 || ORIG_REF_NAME==microBlazeWithSecond_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/microBlazeWithSecond/ip/microBlazeWithSecond_microblaze_0_axi_intc_0/microBlazeWithSecond_microblaze_0_axi_intc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==microBlazeWithSecond_microblaze_0_axi_intc_0 || ORIG_REF_NAME==microBlazeWithSecond_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/microBlazeWithSecond/ip/microBlazeWithSecond_microblaze_0_xlconcat_0/microBlazeWithSecond_microblaze_0_xlconcat_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==microBlazeWithSecond_microblaze_0_xlconcat_0 || ORIG_REF_NAME==microBlazeWithSecond_microblaze_0_xlconcat_0} -quiet] -quiet

# IP: bd/microBlazeWithSecond/ip/microBlazeWithSecond_mdm_1_0/microBlazeWithSecond_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==microBlazeWithSecond_mdm_1_0 || ORIG_REF_NAME==microBlazeWithSecond_mdm_1_0} -quiet] -quiet

# IP: bd/microBlazeWithSecond/ip/microBlazeWithSecond_clk_wiz_1_0/microBlazeWithSecond_clk_wiz_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==microBlazeWithSecond_clk_wiz_1_0 || ORIG_REF_NAME==microBlazeWithSecond_clk_wiz_1_0} -quiet] -quiet

# IP: bd/microBlazeWithSecond/ip/microBlazeWithSecond_rst_clk_wiz_1_100M_0/microBlazeWithSecond_rst_clk_wiz_1_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==microBlazeWithSecond_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==microBlazeWithSecond_rst_clk_wiz_1_100M_0} -quiet] -quiet

# XDC: c:/Studies/Embedded/FPGA/BasicToAdvanced/microBlaze/microBlaze.gen/sources_1/bd/microBlazeWithSecond/microBlazeWithSecond_ooc.xdc
