# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Studies/EmbeddedSystemRepo/Embedded-System/FPGA/libraries/xADC/xADC.srcs/sources_1/ip/xadcSetup/xadcSetup.xci
# IP: The module: 'xadcSetup' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Studies/EmbeddedSystemRepo/Embedded-System/FPGA/libraries/xADC/xADC.gen/sources_1/ip/xadcSetup/xadcSetup_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xadcSetup'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Studies/EmbeddedSystemRepo/Embedded-System/FPGA/libraries/xADC/xADC.gen/sources_1/ip/xadcSetup/xadcSetup.xdc
# XDC: The top module name and the constraint reference have the same name: 'xadcSetup'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Studies/EmbeddedSystemRepo/Embedded-System/FPGA/libraries/xADC/xADC.srcs/sources_1/ip/xadcSetup/xadcSetup.xci
# IP: The module: 'xadcSetup' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Studies/EmbeddedSystemRepo/Embedded-System/FPGA/libraries/xADC/xADC.gen/sources_1/ip/xadcSetup/xadcSetup_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xadcSetup'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Studies/EmbeddedSystemRepo/Embedded-System/FPGA/libraries/xADC/xADC.gen/sources_1/ip/xadcSetup/xadcSetup.xdc
# XDC: The top module name and the constraint reference have the same name: 'xadcSetup'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
